mm-bluelight: Spi Class Reference
Spi Class Reference
#include <spi.h>
Classes
struct SpiDevice
Public Member Functions
Spi (spi_host_device_t host_id, gpio_num_t miso_io_num, gpio_num_t mosi_io_num, gpio_num_t sclk_io_num, int max_transfer_sz)
~Spi ()
int add (uint8_t command_bits, uint8_t address_bits, uint8_t mode, int clock_speed_hz, gpio_num_t spics_io_num, int queue_size)
bool transmit (int index)
spi_transaction_t * transaction (int index)
Private Attributes
spi_host_device_t host_id_
std::vector< SpiDevice * > devices_
Detailed Description
Definition at line 11 of file spi.h.
Constructor & Destructor Documentation
Spi()
Spi::Spi (spi_host_device_t host_id, gpio_num_t miso_io_num, gpio_num_t mosi_io_num, gpio_num_t sclk_io_num, int max_transfer_sz) inline explicit
Definition at line 23 of file spi.h.
~Spi()
Spi::~Spi () inline
Definition at line 36 of file spi.h.
Member Function Documentation
add()
int Spi::add (uint8_t command_bits, uint8_t address_bits, uint8_t mode, int clock_speed_hz, gpio_num_t spics_io_num, int queue_size) inline
Definition at line 44 of file spi.h.
Referenced by Encoder::Encoder(), and Imu::Imu().
transaction()
spi_transaction_t* Spi::transaction (int index) inline
Definition at line 73 of file spi.h.
Referenced by Encoder::Encoder(), Imu::read_byte(), Imu::update(), and Imu::write_byte().
transmit()
bool Spi::transmit (int index) inline
Definition at line 68 of file spi.h.
Referenced by Encoder::Encoder(), Imu::read_byte(), Encoder::update(), Imu::update(), and Imu::write_byte().
Member Data Documentation
devices_
std::vector<SpiDevice *> Spi::devices_ private
Definition at line 20 of file spi.h.
Referenced by add(), transaction(), transmit(), and ~Spi().
host_id_
spi_host_device_t Spi::host_id_ private
Definition at line 19 of file spi.h.
Referenced by add(), and ~Spi().
The documentation for this class was generated from the following file:
main/dri/spi.h