mm-bluelight: Motion Class Reference
Motion Class Reference
#include <motion.h>
Public Member Functions
Motion (Driver *dri, Sensor *sensor)
~Motion ()
rtos::Queue< MotionParameter > & getParameterQueue ()
const MotionParameter & getParameter ()
const MotionTarget & getTarget ()
void update ()
void wait ()
Private Member Functions
bool adjustSideWall (const Sensed &sensed, const MotionParameter &param, MotionTarget &target)
std::pair< float, float > calcMotorVoltage (const Sensed &sensed, const MotionParameter &param, MotionTarget &target)
Static Private Member Functions
static bool setPatternParam (const Sensed &sensed, const MotionParameter &param, MotionTarget &target)
static bool straight (const Sensed &sensed, const MotionParameter &param, MotionTarget &target)
static bool turn (const Sensed &sensed, const MotionParameter &param, MotionTarget &target)
static void calcTargetVelocity (MotionPattern pattern, MotionTarget &target)
Private Attributes
Driver * driver_
Sensor * sensor_
TaskHandle_t handle_notify_ {}
rtos::Queue< MotionParameter > param_queue_ {1}
MotionParameter param_ {}
MotionTarget target_ {}
Pid velo_pid_
Pid ang_velo_pid_
Pid wall_adj_side_pid_
Detailed Description
走行モードに応じた目標値生成・モーターへの反映を行うクラス (Pro CPUで動作)
Definition at line 71 of file motion.h.
Constructor & Destructor Documentation
Motion()
Motion::Motion (Driver * dri, Sensor * sensor) explicit
Definition at line 7 of file motion.cc.
~Motion()
Motion::~Motion () default
Member Function Documentation
adjustSideWall()
bool Motion::adjustSideWall (const Sensed & sensed, const MotionParameter & param, MotionTarget & target) private
Definition at line 99 of file motion.cc.
Referenced by update().
calcMotorVoltage()
std::pair< float, float > Motion::calcMotorVoltage (const Sensed & sensed, const MotionParameter & param, MotionTarget & target) private
Definition at line 123 of file motion.cc.
Referenced by update().
calcTargetVelocity()
void Motion::calcTargetVelocity (MotionPattern pattern, MotionTarget & target) static private
Definition at line 71 of file motion.cc.
Referenced by update().
getParameter()
const MotionParameter& Motion::getParameter () inline
Definition at line 81 of file motion.h.
getParameterQueue()
rtos::Queue<MotionParameter>& Motion::getParameterQueue () inline
Definition at line 79 of file motion.h.
Referenced by Run::stop(), Run::straight(), testEnkaigei(), and Run::turn().
getTarget()
const MotionTarget& Motion::getTarget () inline
Definition at line 84 of file motion.h.
Referenced by printSensor().
setPatternParam()
bool Motion::setPatternParam (const Sensed & sensed, const MotionParameter & param, MotionTarget & target) static private
Definition at line 12 of file motion.cc.
Referenced by update().
straight()
bool Motion::straight (const Sensed & sensed, const MotionParameter & param, MotionTarget & target) static private
Definition at line 29 of file motion.cc.
Referenced by setPatternParam().
turn()
bool Motion::turn (const Sensed & sensed, const MotionParameter & param, MotionTarget & target) static private
Definition at line 64 of file motion.cc.
Referenced by setPatternParam().
update()
void Motion::update ()
Definition at line 154 of file motion.cc.
Referenced by proTask().
wait()
void Motion::wait ()
Definition at line 189 of file motion.cc.
Referenced by Run::stop(), Run::straight(), and Run::turn().
Member Data Documentation
ang_velo_pid_
Pid Motion::ang_velo_pid_ private
Initial value:
{ANGULAR_VELOCITY_PID_GAIN[PARAMETER_PID_KP], ANGULAR_VELOCITY_PID_GAIN[PARAMETER_PID_KI],
                    ANGULAR_VELOCITY_PID_GAIN[PARAMETER_PID_KD]}
Definition at line 113 of file motion.h.
Referenced by calcMotorVoltage(), and update().
driver_
Driver* Motion::driver_ private
Definition at line 94 of file motion.h.
Referenced by update().
handle_notify_
TaskHandle_t Motion::handle_notify_ {} private
Definition at line 100 of file motion.h.
Referenced by update(), and wait().
param_
MotionParameter Motion::param_ {} private
Definition at line 104 of file motion.h.
Referenced by getParameter(), and update().
param_queue_
rtos::Queue<MotionParameter> Motion::param_queue_ {1} private
Definition at line 103 of file motion.h.
Referenced by getParameterQueue(), and update().
sensor_
Sensor* Motion::sensor_ private
Definition at line 97 of file motion.h.
Referenced by update().
target_
MotionTarget Motion::target_ {} private
Definition at line 107 of file motion.h.
Referenced by getTarget(), and update().
velo_pid_
Pid Motion::velo_pid_ private
Initial value:
{VELOCITY_PID_GAIN[PARAMETER_PID_KP], VELOCITY_PID_GAIN[PARAMETER_PID_KI],
                VELOCITY_PID_GAIN[PARAMETER_PID_KD]}
Definition at line 110 of file motion.h.
Referenced by calcMotorVoltage(), and update().
wall_adj_side_pid_
Pid Motion::wall_adj_side_pid_ private
Initial value:
{WALL_ADJUST_SIDE_PID_GAIN[PARAMETER_PID_KP], WALL_ADJUST_SIDE_PID_GAIN[PARAMETER_PID_KI],
                         WALL_ADJUST_SIDE_PID_GAIN[PARAMETER_PID_KD]}
Definition at line 116 of file motion.h.
Referenced by adjustSideWall().
The documentation for this class was generated from the following files:
main/motion.h
main/motion.cc