mm-bluelight: Sensor Class Reference
Sensor Class Reference
#include <sensor.h>
Public Member Functions
Sensor (Driver *dri)
~Sensor ()
void setup ()
void update ()
const Sensed & getSensed ()
void reset ()
Static Public Attributes
static constexpr uint32_t WARM_UP_COUNTS = 10
Private Member Functions
void updateWallSensor (Sensed &sensed)
Private Attributes
Driver * driver_
Odometry odom_
Sensed sensed_ {}
int64_t timestamp_ {}
Detailed Description
センサ値管理・更新を行うクラス
Definition at line 37 of file sensor.h.
Constructor & Destructor Documentation
Sensor()
Sensor::Sensor (Driver * dri) explicit
Definition at line 10 of file sensor.cc.
~Sensor()
Sensor::~Sensor () default
Member Function Documentation
getSensed()
const Sensed& Sensor::getSensed () inline
Definition at line 52 of file sensor.h.
Referenced by printSensor(), selectMode(), and Motion::update().
reset()
void Sensor::reset () inline
Definition at line 55 of file sensor.h.
Referenced by setup(), and Motion::update().
setup()
void Sensor::setup ()
Definition at line 15 of file sensor.cc.
Referenced by proTask().
update()
void Sensor::update ()
Definition at line 53 of file sensor.cc.
Referenced by proTask(), and setup().
updateWallSensor()
void Sensor::updateWallSensor (Sensed & sensed) private
Definition at line 22 of file sensor.cc.
Referenced by update().
Member Data Documentation
driver_
Driver* Sensor::driver_ private
Definition at line 59 of file sensor.h.
Referenced by update(), and updateWallSensor().
odom_
Odometry Sensor::odom_ private
Definition at line 62 of file sensor.h.
Referenced by reset(), and update().
sensed_
Sensed Sensor::sensed_ {} private
Definition at line 65 of file sensor.h.
Referenced by getSensed(), and update().
timestamp_
int64_t Sensor::timestamp_ {} private
Definition at line 68 of file sensor.h.
Referenced by update().
WARM_UP_COUNTS
constexpr uint32_t Sensor::WARM_UP_COUNTS = 10 static constexpr
Definition at line 40 of file sensor.h.
Referenced by setup().
The documentation for this class was generated from the following files:
main/sensor.h
main/sensor.cc